import numpy as np 
#x =  np.arange(2, 11).reshape(3,3)
#x=np.flip(x)
#print(x)
n = np.random.randint(100,size=90)
F = np.array(n)
print("Farenheit: ")
print(F)
print("Centigrados: ") 
print(5*F/9 - 5*32/9)